[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Uncomment and specifiy evm version if need. Helps resolve EvmError: NotActivated error (and possibly others) for example.
# evm_version = "shanghai"

rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth", optimism = "https://opt-mainnet.g.alchemy.com/v2/demo", fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum", bsc = "https://rpc.ankr.com/bsc", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", Avalanche = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon", celo = "https://rpc.ankr.com/celo", Base = "https://developer-access-mainnet.base.org", linea = "https://rpc.linea.build", sepolia = 'https://rpc.sepolia.dev' }

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@uniswap/periphery/contracts=lib/v2-periphery/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
